### ISSUE TITLE
Positioning of items is off

### ISSUE THREAD

**Issue by fredldotme** [ubports/qqc2-suru-style#19]
Qt on edge now properly supports pixel density whereas the QQC2 Suru styling implementation still shows the same issue of positioning items wrongly.
Examples:

Suru style:
![scaleddown_screenshot20190329_135522701](https://user-images.githubusercontent.com/722660/55278698-e13d0c00-530f-11e9-9c9e-beef214be628.png)

compared to Material style:
![scaleddown_screenshot20190330_171444908](https://user-images.githubusercontent.com/722660/55278701-ee59fb00-530f-11e9-97a1-5d255ca02e68.png)

**Comment by bhdouglass** [comment]
Was this an issue before pixel density was supported? Also can you provide some example code or links to the code that is giving this issue?

**Comment by fredldotme** [comment]
This was already an issue before, yes.
I'd suggest looking at the project from the screenshot, recursive clone + clickable should get you there:

https://github.com/fredldotme/harbour-owncloud/tree/accounts+sync

Specifically, FileBrowser.qml and GCButton.qml:
https://github.com/fredldotme/harbour-owncloud/blob/accounts%2Bsync/src/app/qml/qqc/pages/browser/FileBrowser.qml#L474
https://github.com/fredldotme/harbour-owncloud/blob/accounts%2Bsync/src/app/qml/qqc/controls/GCButton.qml

**Comment by bhdouglass** [comment]
I took a look at this today, I can see the issue happening, but I'm not sure why it only happens for Suru style. I'm not seeing any suru related elements in that GCButton. @cibersheep maybe you have an idea?

**Comment by cibersheep** [comment]
I'll take a look today... let's see if I can spot something

**Comment by cibersheep** [comment]
I need to sit down and do some tests. I want to try a couple of things:
 - Check if makes any difference to use [layout.width](https://github.com/fredldotme/harbour-owncloud/blob/master/src/app/qml/qqc/controls/GCButton.qml#L18) but not using RowLayout (at least that I can see)
 - upgrading the versions of import modules (I'm not confident but sometimes they fix bugs)
 
https://doc.qt.io/qt-5/qtquicklayouts-overview.html

**Comment by cibersheep** [comment]
Changing Row { Column {} } by RowLayout { Column {} } makes the app behave similarly with Material and Suru styles. Looks like Row and Column are clashing with the Layouts or we have a wrong style in Suru for it

**Comment by bhdouglass** [comment]
:thinking: interesting. Although I didn't think we were doing anything that would effect the Row.

**Comment by cibersheep** [comment]
I know. I double checked that _we_ are not doing anything to the Row in the style. I remember reading to not mess regular Row with Layouts but I honestly don't know where to look... in the package we serve in the image? We could try to compare the Row element in plain qqc2 and ours, or Android and ours...

**Comment by bhdouglass** [comment]
Ok, I think I fixed it: https://github.com/ubports/qqc2-suru-style/pull/27
Turns out the issue was in the Label component, not the row/column
