### ISSUE TITLE
Border, dividers, lines are gone

### ISSUE THREAD

**Issue by kugiigi** [ubports/qqc2-suru-style#25]
- Channel: Devel and Edge

### Description
The borders, dividers, separator lines, etc. are gone in some qqc2 components.
From what I noticed in my apps, these components are the following:
 - Tumbler
 - Page Header (ToolBar)
 - Text Field
 - SpinBox
 - GroupBox

### Additional Information / Screenshots
Here are some screenshots from my Palitan. You can see here some elements that lose the borders, etc.

![screenshot20190430_173211256](https://user-images.githubusercontent.com/29456786/56956670-1f169580-6b45-11e9-82af-bab907f6bd85.png)
![screenshot20190430_172951097](https://user-images.githubusercontent.com/29456786/56956671-1faf2c00-6b45-11e9-94cc-8f980636a763.png)
![screenshot20190430_173018613](https://user-images.githubusercontent.com/29456786/56956672-1faf2c00-6b45-11e9-9fd5-5737b8aeb1a5.png)
![screenshot20190430_173149685](https://user-images.githubusercontent.com/29456786/56956674-2047c280-6b45-11e9-90d7-05ff17b03f90.png)

**Comment by bhdouglass** [comment]
@cibersheep any idea what happened to them? And/or can you confirm that this is happening?

**Comment by cibersheep** [comment]
I think today I will be able to do some testing :)

**Comment by cibersheep** [comment]
Confirmed on RC channels as well. other styles are ok, so is our fault... I'll try to check commits but I can't remember what _we have done wrong_ 😛

**Comment by cibersheep** [comment]
Suru vs Default styles

![screenshot20190503_110722505](https://user-images.githubusercontent.com/6640041/57134873-cdba1080-6da7-11e9-96b0-c4bdcf36050e.png)
![screenshot20190503_110742169](https://user-images.githubusercontent.com/6640041/57134874-cdba1080-6da7-11e9-8c46-7c5c8afd421b.png)

**Comment by bhdouglass** [comment]
Would this PR have anything to do with it @cibersheep ? https://github.com/ubports/qqc2-suru-style/pull/24/files

**Comment by cibersheep** [comment]
Mmmm... border should be [neutralColor](https://github.com/ubports/qqc2-suru-style/blob/xenial/qqc2-suru/GroupBox.qml#L65) that should be untouched?
I'll try to do a test tomorrow?

**Comment by bhdouglass** [comment]
Fixed this here: https://github.com/ubports/qqc2-suru-style/commit/753661bf51fe3438efda41da4a6e03a2d58b4ef7

Apparently when you have auto scaling enabled it made the borders a 0 width.

**Comment by cibersheep** [comment]
Well catched!

**Comment by cibersheep** [comment]
We can close this, right?

**Comment by bhdouglass** [comment]
Closed!
