### ISSUE TITLE
Suru Theme Dial controls oversized

### ISSUE THREAD

**Issue by lduboeuf** [ubports/qqc2-suru-style#29]
hi, just tested a page with Dial controls.
Size seems to be fine in System theme but not in Suru (overlaps). i've tried either by defining `width` and `height` in Dial and `implicitWidth` and `implicitHeight` ). 

![screenshot20190528_103810049](https://user-images.githubusercontent.com/11663835/58464291-b9aec800-8135-11e9-8ad5-515f8f1b5cf7.png)
![screenshot20190528_103734351](https://user-images.githubusercontent.com/11663835/58464312-bfa4a900-8135-11e9-8cbb-b63c847914ba.png)

**Comment by cibersheep** [comment]
Mmm... interesting. On what device are you on?
What element are you using? Do you have a link to the code?

**Comment by lduboeuf** [comment]
i'm on Nexus 5.
You can find an example here: https://github.com/lduboeuf/sfxr-qt/blob/master/ui/SliderGroup.qml#L71 
bascally, it is Dial controls within a gridLayout

**Comment by lduboeuf** [comment]
i've tested to force a width/height or implicitWidth/implicitHeight to a low value, and nothing is taken into account

**Comment by bhdouglass** [comment]
So the problem here is that the background for the dial (which is the actual circle) has a minimum size of 192 which is bigger than the size you want to set your in that app. I updated it in #30 to 64 which is what is being used in the material design style. Which makes your app look correct.

**Comment by cibersheep** [comment]
Was this fixed?

**Comment by lduboeuf** [comment]
Is it merged to mainstream ? Not tested it personnaly

**Comment by bhdouglass** [comment]
Yeah this should be available for testing on the latest UT release. Feel free to reopen if the issue isn't resolved.
