### ISSUE TITLE
Suru Label changes QQC2 Label default wrap mode

### ISSUE THREAD

**Issue by rinigus** [ubports/qqc2-suru-style#32]
In QQC2, wordWrap is set to None by default (https://doc.qt.io/qt-5/qml-qtquick-text.html#wrapMode-prop). Suru style redefines that default and sets it to WordWrap (https://github.com/ubports/qqc2-suru-style/blob/xenial/qqc2-suru/Label.qml#L35). As a result, apps assuming that Label is a single-line text unless specified otherwise, are getting strange issues (https://github.com/rinigus/pure-maps/issues/304). Please restore QQC2 default.

**Comment by bhdouglass** [comment]
@cibersheep any objections to making this change? It's probably best not to mess with the default like that.

**Comment by cibersheep** [comment]
Not at all. We agreed to go the _upstreamest_ we could :)

**Comment by bhdouglass** [comment]
:point_up: made a PR to address this!

**Comment by bhdouglass** [comment]
A fix will be out in the next OTA!
