### ISSUE TITLE
Add Private headers to project

### ISSUE THREAD

**Issue by MohsenNz** [ubports/qqc2-suru-style#34]
Cause of the qt private headers have no guaranty to reserve API , Is good idea to adding one of this to project?

**Comment by bhdouglass** [comment]
I agree, it is less than desirable, but it looks like the upstream styles also do this so there may not be a good way around using the private headers. If anyone know a way around that I'd be happy to learn!

**Comment by JBBgameich** [comment]
The KDE styles (https://github.com/KDE/qqc2-desktop-style, https://github.com/KDE/plasma-framework/tree/master/src/declarativeimports/plasmacomponents3) don't seem to use private headers but I haven't looked into how their features are exactly replaced.

**Comment by bhdouglass** [comment]
@JBBgameich do you know what base classes are being used when setting up the qqc2 style?

**Comment by MohsenNz** [comment]
I'm working on new Suru Style (name Suru2). https://gitlab.gnome.org/mohsenNz/qqc2-suru2-style

**Comment by bhdouglass** [comment]
Rather than maintaining a separate fork would you be interested in collaborating with us here?

**Comment by MohsenNz** [comment]
Yeah, I like, but I have do major changes on my fork , I think you don't want it. ( like attached properties, colors properties, etc...)
Is possible do these on a develop branch ?  
if possible so i want to collaborate with us.

**Comment by bhdouglass** [comment]
We are definitely open to collaboration to make this better! If you want, you could make some PRs for various changes and we can discuss including them there. And we can make whatever branches are needed to support the different qt versions 👍

**Comment by MohsenNz** [comment]
Thank you. Since my code is different from here, can put these codes in a branch here?
or should work on my fork an make PRs where needed?

**Comment by bhdouglass** [comment]
Lets start with PRs and go from there
