### ISSUE TITLE
cannot get ComboBox editable

### ISSUE THREAD

**Issue by wdehoog** [ubports/qqc2-suru-style#43]
When setting 'editable' to true for a ComboBox it has no effect. Could it be due to the style for ComboBox using a 'Text' field which is a readonly text component?

**Comment by cibersheep** [comment]
There is no ComboBox in the toolkit, there is a [ComboButton](https://api-docs.ubports.com/sdk/apps/qml/Ubuntu.Components/ComboButton.html)

but the hole idea of the Combo elements is to replace an editable text therefore are read only ([example](https://github.com/Jujuyeh/webapp-creator/blob/main/webapp-creator/app/Main.qml#L842)).

You could use a TextField and a ComboButton underneath linked to it

**Comment by wdehoog** [comment]
I think an editable combobox is a very usefull control. For example when having a search text field with history.

Your 'hole idea' link points to an editable combobox by the way and the 'example'  link does not resolve.

Do you know of an example of a linked  TextField and ComboBox?

**Comment by cibersheep** [comment]
Thank you
