### ISSUE TITLE
background width of TextField 

### ISSUE THREAD

**Issue by wdehoog** [ubports/qqc2-suru-style#44]
When I have a textfield with a large width the border is too small (ending somewhere before the end of the control).
 
I added 
```
                    Component.onCompleted: {
                        background.width = width
                    }
```
to have the border surround the complete control.

**Comment by cibersheep** [comment]
Could you add a screenshot?

**Comment by wdehoog** [comment]
The search field is a text field with a combobox behind it. Its border is now halfway but with my trick it is next to the combobox indicator. Code is here https://github.com/wdehoog/donnie-ubports/blob/7b3eda9d6c0cdb569277a048fcf74e63ee9068fe/qml/pages/Search.qml#L164

With  clickable desktop it works correct but on my phone (opo on devel) this error occurs.

![screenshot20200524_232643300](https://user-images.githubusercontent.com/3353303/82765360-75bcd480-9e16-11ea-9152-de92385ccaad.png)

**Comment by cibersheep** [comment]
I see. Thank you

**Comment by bhdouglass** [comment]
@wdehoog could you provide a minimal example of this issue? I wasn't able to compile your app and I'm not able to reproduce the issue.

**Comment by wdehoog** [comment]
@bhdouglass I created an example with only the textfield, button and two comboboxes and ofcourse now it works as expected. 
Too bad compiling donnie failed for you. I'll close the issue until I have a failing example.

**Comment by bhdouglass** [comment]
Sounds good, feel free to reopen if you run into it again!
