### ISSUE TITLE
Ubuntu UI Toolkit Button with strokeColor has unreadable text in dark mode

### ISSUE THREAD

**Issue by wdehoog** [ubports/qqc2-suru-style#46]
See Ubuntu UI Toolkit App. Switch to dark mode and open the Buttons page. 
The 'Stroke' button has dark text on dark background.

**Comment by cibersheep** [comment]
Is it happening both with uuitk and qqc2? Only with qqc2 apps?

**Comment by wdehoog** [comment]
I noticed it with my uitk app and checked it with the UITK gallery app. qqc2 Buttons do not seem to have this property.

**Comment by cibersheep** [comment]
I see. Thank you. 
This repo is only for the qqc2. The one for uuitk is here: https://github.com/ubports/ubuntu-ui-toolkit

**Comment by wdehoog** [comment]
@cibersheep sorry and thanks.
