### ISSUE TITLE
Qt 5.12: ElevationEffect is not a type

### ISSUE THREAD

**Issue by jonnius** [ubports/qqc2-suru-style#53]
Dekko runs into *ElevationEffect is not a type* in [Dialog.qml:68](qqc2-suru/Dialog.qml#L68). See [Dekko Issue](https://gitlab.com/dekkan/dekko/-/merge_requests/119) for reference.

**Comment by cibersheep** [comment]
QQC2 Gallery show all dialogs correctly (E5)

**Comment by jonnius** [comment]
Dekko runs fine (was affected by this issue before).
