### ISSUE TITLE
Dark mode issues

### ISSUE THREAD

**Issue by kugiigi** [ubports/qqc2-suru-style#7]
## Description
Add a Spinbox. Set the Suru.theme to Suru.Dark
The label is still black and cannot be seen in dark mode.

**Comment by bhdouglass** [comment]
These elements have similar issues in dark mode:

- SpinBox
- Switch
- RadioButton
- PageIndicator
- RangeSlider
- Slider
- TextArea
- TextField

@cibersheep could you take a look at this sometime?

**Comment by cibersheep** [comment]
That sounds like adult fun

**Comment by cibersheep** [comment]
Update:

[x] SpinBox (Balcy)
[x] Switch (was already fixed?)
[x] RadioButton (already fixed?)
[x] PageIndicator (idem)
[x] RangeSlider (#36)
[x] Slider (#36)
[x] TextArea (already fixed?)
[x] TextField (already fixed?)

![imatge](https://user-images.githubusercontent.com/6640041/70574256-fb6c0100-1ba3-11ea-8531-95d4c58da42c.png)
![imatge](https://user-images.githubusercontent.com/6640041/70574288-12125800-1ba4-11ea-81da-eb741d6bb8d4.png)

**Comment by bhdouglass** [comment]
The only thing I see left to do is the message dialog, it doesn't have any shadow like the light version. :+1:

**Comment by cibersheep** [comment]
> The only thing I see left to do is the message dialog, it doesn't have any shadow like the light version. +1

Thanks. I'll take a look tomorrow :)

**Comment by cibersheep** [comment]
Today might be tomorrow already :D

**Comment by Flaburgan** [comment]
Hi, maybe this is a bug in UTTT but I noticed that some checkboxes there have this problem too:
![screenshot20191229_233528415](https://user-images.githubusercontent.com/930064/71563725-81d57d80-2a94-11ea-8232-6ab73e3c1c30.png)
This is from the app screen, to erase cache and data. I was unable to see the checkbox, being outside with some sunlight. In the screenshot you can see some borders, but the contrast is too low in real life. Checkboxes' background should be white.

**Comment by bhdouglass** [comment]
@Flaburgan I just checked out the code for UTTT, looks like it's using the ubuntu touch ui toolkit rather than qt quick controls 2 with suru style. Can you report and issue over here: https://github.com/ubports/ubuntu-ui-toolkit/issues ? Thanks!
